-- Lua is the most stupid things ever, this clusterfuck was originally generated by a script but the fucking retard who made it didn't know how to do loops or functions so here we are, 300 lines of dl.general like a fucking clanker because whever they are under one function the device shits itself and send over 50 errors

---@module 'hl'

--$monitor1 = HDMI-A-1

local monitor1 = "eDP-1"

-- Configure Monitors

hl.monitor({
	output = monitor1,
	mode = "1920x1080@60",
	position = "0x0",
	scale = 1,
})

--monitor=$monitor2,1920x1080@60,0x0,1

-- Workspaces (created on demand, bound to monitor via dispatchers)

hl.on("hyprland.start", function()
	hl.exec_cmd("waybar")
	hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("hyprpaper")
	hl.exec_cmd("hyprctl dispatch workspace 1")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("wl-paste --type text --watch cliphist store")
	hl.exec_cmd("wl-paste --type image --watch cliphist store")
	hl.exec_cmd("hyprctl keyword input:touchpad:middle_button_emulation false")
	hl.exec_cmd("hyprctl keyword input:touchpad:clickfinger_behavior true")

	hl.exec_cmd("/usr/lib/kdeconnectd")
	hl.exec_cmd("kdeconnect-indicator")
end)

-- Source a file (multi-file configs)
-- source = ~/.config/hypr/myColors.conf

-- Set programs that you use

local terminal = "kitty"
local fileManager = "kitty -e yazi"
local menu = "rofi -show drun -config ~/.config/rofi/config.rasi"
local mainMod = "SUPER"

-- Some default env vars.

hl.env("XCURSOR_SIZE", "24")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")

-- For all categories, see https://wiki.hyprland.org/Configuring/Variables/

hl.config({
	input = {
		kb_layout = "us",
		kb_variant = "",
		--kb_layout = latam
		follow_mouse = 1,
		touchpad = {
			natural_scroll = false,
			-- clickfinger_behavior = true,
		},
		accel_profile = "flat",
		sensitivity = 0,
		-- -1.0 to 1.0, 0 means no modification.
	},
	general = {
		-- See https://wiki.hyprland.org/Configuring/Variables/ for more
		gaps_in = 0,
		gaps_out = 0,
		border_size = 2,
		["col.active_border"] = "rgb(89b482)",
		["col.inactive_border"] = "rgb(d3c6aa)",
		layout = "dwindle",
		-- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
		allow_tearing = false,
	},
	decoration = {
		rounding = 0,
		blur = {
			enabled = false,
			size = 3,
			passes = 3,
			new_optimizations = true,
			ignore_opacity = true,
			noise = 0,
		},
	},
	animations = {
		enabled = false,
		-- Movement/scale (without changing opacity)
		-- Layers without fade (prevents flashes in menus/overlays)
		-- Workspaces without pure "fade" (safer)
		-- KEY: disable the entire fade branch (avoids wallpaper frame flash)
	},
	master = {
		-- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
		new_status = "master",
	},
	gestures = {
		-- See https://wiki.hyprland.org/Configuring/Variables/ for more
		-- workspace_swipe = off
	},
	misc = {
		-- See https://wiki.hyprland.org/Configuring/Variables/ for more
		force_default_wallpaper = -1,
		middle_click_paste = false,
		--vfr = true,
		-- Set to 0 or 1 to disable the anime mascot wallpapers
	},
})

-- Example per-device config

-- See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
-- hl.config({
-- 	input = {
-- 		touchpad = {
-- 			middle_click_emulation = false,
-- 			clickfinger_behaviour = false,
-- 		},
-- 	},
-- })

-- Example windowrule v1

-- windowrule = float, ^(kitty)$

-- Example windowrule v2

-- windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

hl.window_rule({
	name = "suppress_event_maxim",
	match = {
		class = ".*",
	},
	suppress_event = "maximize",
})

hl.window_rule({
	match = {
		class = "^(SkyrimSE.exe)$",
	},
	float = true,
	center = true,
})

-- You'll probably like this.

-- bind for change keyboard layout

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "R", hl.dsp.exec_cmd("hyprctl switchxkblayout current next"))

-- screenshot

-- bind = $mainMod, S, exec, grim -g "$(slurp)"

-- bind = $mainMod, S, exec, hyprshot -z -m region

-- bind = $mainMod, S, exec, grim -g "$(slurp)" ~/Documentos/imagenes/screenshots/captura_$(date +%Y_%m_%d).png

-- bind for take a screenshot and copy it to clipboard

hl.bind(mainMod .. " + " .. "S", hl.dsp.exec_cmd("hyprshot -m region --freeze"))

-- bind for clipboard history

hl.bind(
	mainMod .. " + " .. "SHIFT" .. " + " .. "V",
	hl.dsp.exec_cmd("cliphist list| rofi -dmenu| cliphist decode| wl-copy")
)

-- bind for wifi rofi menu

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "W", hl.dsp.exec_cmd("~/.config/rofi/rofi-wifi-menu.sh"))

-- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more

hl.bind(mainMod .. " + " .. "Return", hl.dsp.exec_cmd("kitty"))

hl.bind(mainMod .. " + " .. "Q", hl.dsp.window.close())

hl.bind(mainMod .. " + " .. "M", hl.dsp.exec_cmd("~/.config/rofi/rofi-power-menu.sh"))

hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd("kitty -e yazi"))

hl.bind(mainMod .. " + " .. "V", hl.dsp.window.float())

hl.bind(mainMod .. " + " .. "D", hl.dsp.exec_cmd(menu))

hl.bind(mainMod .. " + " .. "C", hl.dsp.exec_cmd("code"))

hl.bind(mainMod .. " + " .. "o", hl.dsp.exec_cmd("obsidian"))

-- dwindle

-- bind = $mainMod, T, togglesplit, # dwindle

hl.bind(mainMod .. " + " .. "B", hl.dsp.exec_cmd("firefox"))

hl.bind(mainMod .. " + " .. "N", hl.dsp.exec_cmd("rnote"))

hl.bind(mainMod .. " + " .. "X", hl.dsp.exec_cmd("hyprlock"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "D", hl.dsp.exec_cmd("vesktop"))

-- Volume Control (using wpctl from Pipewire)

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+"))

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"))

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"))

-- the mic mute is set differently because this laptop sucks ass

-- Mic mute toggle (Universal)

hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true })

-- Fallback/Custom bind

-- Ensure SUPER+F4 toggles the same microphone nodes as the hardware F4
hl.bind(
	mainMod .. " + " .. "F4",
	hl.dsp.exec_cmd("setsid sh ~/.local/bin/toggle-mic.sh >/dev/null 2>&1 &"),
	{ locked = true }
)

-- Bind plain F4 (hardware key on this device) to toggle microphone mute
-- Toggle both possible microphone nodes (61 and 62) to ensure hardware F4 mutes active source
hl.bind("F4", hl.dsp.exec_cmd("setsid sh ~/.local/bin/toggle-mic.sh >/dev/null 2>&1 &"))

-- Brightness Control (using brightnessctl)

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set 5%+"))

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 5%-"))

-- Screenshot a window

--bind = $mainMod, PRINT, exec, hyprshot -m window

-- Screenshot a monitor

--bind = , PRINT, exec, hyprshot -m output

-- Screenshot a region

--bind = $shiftMod, PRINT, exec, hyprshot -m region

-- Move windows

hl.bind("SUPER + H", hl.dsp.window.move({ direction = "l" }))

hl.bind("SUPER + L", hl.dsp.window.move({ direction = "r" }))

hl.bind("SUPER + K", hl.dsp.window.move({ direction = "u" }))

hl.bind("SUPER + J", hl.dsp.window.move({ direction = "d" }))

-- Resize windows

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "h", hl.dsp.window.resize({ x = -100, y = 0, relative = true }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "l", hl.dsp.window.resize({ x = 100, y = 0, relative = true }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "k", hl.dsp.window.resize({ x = 0, y = -100, relative = true }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "j", hl.dsp.window.resize({ x = 0, y = 40, relative = true }))

-- Move focus with mainMod + arrow keys

hl.bind(mainMod .. " + " .. "left", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "right", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "up", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "down", hl.dsp.focus({ direction = "down" }))

-- Move focus to the previus workspaces

hl.bind(mainMod .. " + " .. "Tab", hl.dsp.focus({ workspace = "r+1" }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Tab", hl.dsp.focus({ workspace = "r-1" }))

-- Switch workspaces with mainMod + [0-9]

hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

-- Example special workspace (scratchpad)

hl.bind(mainMod .. " + " .. "Space", hl.dsp.workspace.toggle_special("magic"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Fullscreen window

hl.bind(mainMod .. " + " .. "F", hl.dsp.window.fullscreen())

-- ALT + Tab

hl.bind("ALT" .. " + " .. "Tab", hl.dsp.window.cycle_next())

hl.bind("ALT" .. " + " .. "SHIFT" .. " + " .. "Tab", hl.dsp.window.bring_to_top())

-- Shortcut to neovim

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "N", hl.dsp.exec_cmd("kitty nvim"))

-- bind to level up or down the volume of spotify

--bind = $mainMod, U, exec, playerctl -p spotify volume 0.1-

--bind = $mainMod, I, exec, playerctl -p spotify volume 0.1+

-- bind to control music

--bind = $mainMod, Right, exec, playerctl -p spotify next

--bind = $mainMod, Left, exec, playerctl -p spotify previous

-- ==========================================

-- Window Rules - NEW SYNTAX FOR v0.53+

-- ==========================================

-- Workspace assignments

--windowrule = workspace 6, match:class ^(Spotify)$

--windowrule = workspace 7, match:class ^(vesktop)$

-- Opacity rules (commented out - uncomment if needed)

-- windowrule = opacity 0.8, match:class ^(obsidian)$

-- windowrule = opacity 0.75, match:class ^(Spotify)$

-- windowrule = opacity 0.83, match:class ^(vesktop)$

-- windowrule = opacity 0.90, match:class ^(org\.pwmt\.zathura)$

-- windowrule = opacity 0.80, match:class ^(pcmanfm-qt)$

-- windowrule = opacity 0.90, match:class ^(Code)$

-- Float and size rules

-- KeePassXC: open on ws1, float, fixed size, centered
hl.window_rule({
	match = {
		class = "^(org\\.keepassxc\\.KeePassXC)$",
	},
	suppress_event = "maximize",
	workspace = 1,
	float = true,
	size = { 1100, 650 },
	center = true,
})

hl.window_rule({
	match = {
		class = "^(feh)$",
	},
	float = true,
})

hl.window_rule({
	match = {
		class = "^(feh)$",
	},
	size = { 960, 540 },
})

hl.window_rule({
	match = {
		class = "^(feh)$",
	},
	center = true,
})

hl.window_rule({
	match = {
		class = "^(vlc)$",
	},
	float = true,
})

-- Steam window rules
hl.window_rule({
	match = {
		class = "steam",
		title = "Friends List",
	},
	size = "30% 100%",
})

hl.window_rule({
	match = {
		class = "steam",
		title = "Steam",
	},
	size = "70% 100%",
})

-- ==========================================

-- Layer Rules - NEW SYNTAX FOR v0.53+

-- ==========================================

-- Disable animations for screenshots and selection tool
hl.layer_rule({
	match = {
		namespace = "^(hyprpicker)$",
	},
	no_anim = true,
})

hl.layer_rule({
	match = {
		namespace = "^(selection)$",
	},
	no_anim = true,
})

-- GTK theme settings
hl.exec_cmd("gsettings set org.gnome.desktop.interface gtk-theme Adwaita")
hl.exec_cmd("gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'")

-- Bind for lid switch events
hl.bind("switch:on:Lid Switch", hl.dsp.exec_cmd("~/.config/hypr/scripts/lid_handler.sh close"), { locked = true })
hl.bind("switch:off:Lid Switch", hl.dsp.exec_cmd("~/.config/hypr/scripts/lid_handler.sh open"), { locked = true })
