return function()
    hl.on("hyprland.start", function()
        hl.exec_cmd("pgrep -x waybar >/dev/null || waybar")
        hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE XDG_SESSION_DESKTOP")
        hl.exec_cmd("pgrep -x hyprpaper >/dev/null || hyprpaper")
        hl.exec_cmd("sleep 10; pgrep -x keepassxc >/dev/null || keepassxc")
        hl.exec_cmd("hyprctl dispatch workspace 1")
        hl.exec_cmd("pgrep -x hypridle >/dev/null || hypridle")
        hl.exec_cmd("wl-paste --type text --watch cliphist store")
        hl.exec_cmd("wl-paste --type image --watch cliphist store")
        hl.exec_cmd("hyprctl keyword input:touchpad:middle_button_emulation false")
        hl.exec_cmd("/usr/lib/kdeconnectd")
        hl.exec_cmd("kdeconnect-indicator")
    end)
end